spring:
  datasource:
    url: ${MTM_DB_URL:jdbc:mysql://db:3306/mtm?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Shanghai}
    username: ${MTM_DB_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD}
# Redis Configuration
custom-redis:
  host: ${MTM_REDIS_HOST:mid}
# Elasticsearch Configuration
elasticsearch:
  host: ${MTM_ELASTICSEARCH_HOST:es}
