spring:
  profiles:
    active: @profileActive@
  application:
    name: mtm
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver # MySQL Version 5
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Version 8
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    username: # Your Email Address. For Instance: abc@email.com
    password: # Your Email Password.
    host: # Your Email Host. For Instance: smtp.xxx.com
  sa-token:
    # Create separate tokens for each user when they login with the same account
    is-share: false
server:
  port: 8080
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
mybatis:
  type-aliases-package: com.github.learndifferent.mtm.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# Elasticsearch Configuration
elasticsearch:
  port: 9200
  scheme-name: http
# Async Configuration
custom-async:
  core-pool-size: 3
  alive-seconds: 30
  queue-capacity: 50
# Redis Configuration
custom-redis:
  port: 6379
  cache-configs:
    "[comment:count]": 10
    "[user:name]": 10
    "[tag:all]": 10
    "[tag:popular]": 10
    "[empty:user:all]": 20
    "system:log": 40
    "[bookmarks:visited]": 0
    "[tag:a]": 0
# IdempotencyCheck Configuration
idempotency-config:
  timeout: 3
  key: mtm-idempotency-key