spring:
  profiles:
    active: dev
  application:
    name: web
  datasource:
    #  driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Version 8
    driver-class-name: com.mysql.jdbc.Driver # MySQL Version 5
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    username: # Your Email Address. For Instance: abc@email.com
    password: # Your Email Password.
    host: # Your Email Host. For Instance: smtp.xxx.com
  sa-token:
    # create separate tokens for each user when they login with the same account
    is-share: false
server:
  port: 80
mybatis:
  type-aliases-package: com.github.learndifferent.mtm.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# Elasticsearch Configuration
elasticsearch:
  port: 9200
  scheme-name: http
# Async Configuration
custom-async:
  core-pool-size: 3
  alive-seconds: 30
  queue-capacity: 50
# Redis Configuration
custom-redis:
  port: 6379
  cache-configs:
    "[comment:count]": 10
    "[user:name]": 10
    "[tag:all]": 10
    "[tag:popular]": 10
    "[empty:user:all]": 20
    "system-log": 40
    "[bookmarks:visited]": 0
    "[tag:a]": 0
---
spring:
  profiles: prod
  datasource:
    # "db" is the host of MySQL
    url: jdbc:mysql://db:3306/mtm?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: LearnDifferent
# Redis Configuration
custom-redis:
  host: mid
elasticsearch:
  host: es
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mtm?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
# Redis Configuration
custom-redis:
  host: localhost
elasticsearch:
  host: localhost
logging:
  level:
    com:
      github:
        learndifferent:
          mtm:
            mapper: debug