spring:
  profiles:
    active: @profileActive@
  application:
    name: mtm
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver # MySQL Version 5
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Version 8
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    username: # Your Email Address. For Instance: abc@email.com
    password: # Your Email Password.
    host: # Your Email Host. For Instance: smtp.xxx.com
  sa-token:
    # Create separate tokens for each user when they login with the same account
    is-share: false
server:
  port: 8080
mybatis:
  type-aliases-package: com.github.learndifferent.mtm.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# Elasticsearch Configuration
elasticsearch:
  port: 9200
  scheme-name: http
# Async Configuration
custom-async:
  core-pool-size: 3
  alive-seconds: 30
  queue-capacity: 50
# Redis Key Configuration
custom-redis:
  port: 6379
  cache-configs:
    # Key Constant
    COMMENT_COUNT:
      # Redis Key: ttl
      # Map<String, Map<String, Long>>
      # e.g. {COMMENT_COUNT: {comment:count : 10} }
      "[comment:count]": 10
    USER_NAME:
      "[user:name]": 10
    TAG_ALL:
      "[tag:all]": 10
    TAG_POPULAR:
      "[tag:popular]": 10
    EMPTY_USER_ALL:
      "[empty:user:all]": 20
    SYSTEM_LOG:
      "[system:log]": 40
    BOOKMARK_VISITED:
      "[bookmarks:visited]": 0
    TAG_ONE:
      "[tag:one]": 0
# IdempotencyCheck Configuration
idempotency-config:
  timeout: 35
  key: mtm-idempotency-key