spring:
  application:
    name: web
  datasource:
    #  driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Version 8
    driver-class-name: com.mysql.jdbc.Driver # MySQL Version 5
    type: com.alibaba.druid.pool.DruidDataSource
    # "db" is the host of MySQL. It can be replace by "localhost"
    url: jdbc:mysql://db:3306/mtm?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
  mail:
    username: # Your Email. For Instance: abc@email.com
    password: # Your Email Password.
    host: # Your Email Host. For Instance: smtp.xxx.com
  sa-token:
    # create separate tokens for each user when they login with the same account
    is-share: false
server:
  port: 80
mybatis:
  type-aliases-package: com.github.learndifferent.mtm.pojo
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      github:
        learndifferent:
          mtm:
            mapper: debug
# Elasticsearch
elasticsearch:
  host: es
  port: 9200
  isHttps: false
# Initialize WebFilterRequest.java
website-filter:
  load: 10
  order: "userName"
  isDesc: false
# Async Configuration
custom-async:
  core-pool-size: 3
  alive-seconds: 30
  queue-capacity: 50
