spring:
  application:
    name: web
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver # 版本 8
    driver-class-name: com.mysql.jdbc.Driver # 版本 5
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://db:3306/mtm?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
  mail:
    username: # 填入自己的 email
    password: # 填入自己的 password
    host: # 填入自己的 host，如 smtp.xxx.com
server:
  port: 80
mybatis:
  type-aliases-package: com.github.learndifferent.mtm.pojo
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      github:
        learndifferent:
          mtm:
            mapper: debug
# Elasticsearch
elasticsearch:
  host: es
  port: 9200
  isHttps: false
# 筛选 Website 数据的 Filter 类的初始值
website-filter:
  load: 10
  order: "userName"
  isDesc: false
# 自定义的异步配置
custom-async:
  core-pool-size: 3
  alive-seconds: 30
  queue-capacity: 50
