spring:
  datasource:
    url: ${MTM_DB_URL:jdbc:mysql://localhost:3306/mtm?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Shanghai}
    username: ${MTM_DB_USERNAME:root}
    password: ${MTM_DB_PASSWORD:rootroot}
# Redis Configuration
custom-redis:
  host: ${MTM_REDIS_HOST:localhost}
# Elasticsearch Configuration
elasticsearch:
  host: ${MTM_ELASTICSEARCH_HOST:localhost}
logging:
  level:
    com:
      github:
        learndifferent:
          mtm:
            mapper: debug
