package com.github.learndifferent.mtm.controller;

import com.github.learndifferent.mtm.config.mvc.CustomWebConfig;
import com.github.learndifferent.mtm.query.BasicWebDataRequest;
import com.github.learndifferent.mtm.service.impl.BookmarkServiceImpl;
import com.github.learndifferent.mtm.utils.LoginUtils;
import com.github.learndifferent.mtm.vo.BookmarkVO;
import java.io.File;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentMatchers;
import org.mockito.BDDMockito;
import org.mockito.MockedStatic;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;

/**
 * Web MVC test for BookmarkController using JUnit 5
 * Note: The following comments are generated by Cursor AI
 */
@WebMvcTest(BookmarkController.class)
class BookmarkControllerTest {

    // Auto-inject MockMvc instance using @Autowired
    @Autowired
    // MockMvc is used to simulate HTTP requests in tests
    private MockMvc mockMvc;

    @MockBean
    private BookmarkServiceImpl bookmarkService;

    @MockBean
    private CustomWebConfig config;

    /**
     * Test method to check if calling /bookmark endpoint returns status code 200
     *
     * @throws Exception if an exception occurs
     */
    @Test
    @DisplayName("Should return result code of 200")
    void shouldReturnResultCodeOf200() throws Exception {

        // Read request body data from resource file
        URL resource = BookmarkControllerTest.class.getClassLoader()
                .getResource("request" + File.separator
                        + "bookmark" + File.separator
                        + "basic-bookmark-data.json");
        assert resource != null;
        Path path = Paths.get(resource.toURI());
        byte[] requestBody = Files.readAllBytes(path);

        // Use Mockito.mockStatic to mock LoginUtils.getCurrentUserId method
        try (MockedStatic<LoginUtils> loginUtilsMockedStatic = Mockito.mockStatic(LoginUtils.class)) {

            loginUtilsMockedStatic.when(LoginUtils::getCurrentUserId).thenReturn(1L);

            // Use BDDMockito.given to set up expected behavior for bookmarkService.addToBookmark
            BDDMockito.given(bookmarkService.addToBookmark(
                            ArgumentMatchers.any(BasicWebDataRequest.class), ArgumentMatchers.anyLong()))
                    .willReturn(true);

            // Use mockMvc.perform to simulate a POST request and check response status code and JSON path
            mockMvc.perform(
                            MockMvcRequestBuilders
                                    // Simulate POST request
                                    .post("/bookmark")
                                    // Set request body
                                    .content(requestBody)
                                    // Set content type to JSON
                                    .contentType(MediaType.APPLICATION_JSON)
                    ).andExpect(MockMvcResultMatchers.status().isOk())
                    .andExpect(MockMvcResultMatchers.jsonPath("$.code").value(200));
        }
    }

    @Test
    @DisplayName("Should return the bookmark with the same ID")
    void shouldReturnTheBookmarkWithSameId() throws Exception {
        long currentUserId = 1L;
        Long id = 1L;
        BookmarkVO bookmark = new BookmarkVO();
        bookmark.setId(id);

        try (MockedStatic<LoginUtils> loginUtilsMockedStatic = Mockito.mockStatic(LoginUtils.class)) {
            loginUtilsMockedStatic.when(LoginUtils::getCurrentUserId).thenReturn(currentUserId);
            BDDMockito.given(bookmarkService.getBookmark(id, currentUserId))
                    .willReturn(bookmark);

            // Use mockMvc.perform to simulate a GET request and check response status code and JSON path
            mockMvc.perform(
                            MockMvcRequestBuilders
                                    .get("/bookmark/get")
                                    .param("id", "1"))
                    .andExpect(MockMvcResultMatchers.status().isOk())
                    .andExpect(MockMvcResultMatchers
                            .jsonPath("$.id")
                            .value(id));
        }
    }
}
