package com.github.learndifferent.mtm.controller;

import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.mockStatic;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.github.learndifferent.mtm.config.mvc.CustomWebConfig;
import com.github.learndifferent.mtm.service.impl.CommentServiceImpl;
import com.github.learndifferent.mtm.utils.LoginUtils;
import com.github.learndifferent.mtm.vo.CommentVO;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.web.servlet.MockMvc;


/**
 * Web MVC test for CommentController
 * Note: The following comments are generated by Cursor AI
 */
@WebMvcTest(CommentController.class)
class CommentControllerTest {

    // Auto-inject MockMvc instance using @Autowired
    @Autowired
    // MockMvc is used to simulate HTTP requests in tests
    private MockMvc mockMvc;

    // Create mock object for CommentServiceImpl using @MockBean
    @MockBean
    // This mock object will replace the actual service class in tests
    private CommentServiceImpl commentService;

    // This mock object will replace the actual configuration class in tests
    @MockBean
    private CustomWebConfig config;

    @Nested
    class GetCommentById {

        /**
         * Comment ID
         */
        private final long ID = 100L;
        private final CommentVO COMMENT = new CommentVO().setId(ID);
        private final long BOOKMARK_ID = 1L;
        private final long USER_ID = 1L;

        @BeforeEach
        void setUp() {
            // Set up mock object behavior using BDDMockito.given
            // willReturn specifies the value to return when the method is called
            given(commentService.getCommentByIds(ID, BOOKMARK_ID, USER_ID))
                    .willReturn(COMMENT);
        }

        @Test
        @DisplayName("Should return the comment")
        void shouldReturnTheComment() throws Exception {

            // Create mock for static methods of LoginUtils using Mockito.mockStatic
            // This mock will replace actual static methods in tests
            try (MockedStatic<LoginUtils> loginUtilsMockedStatic = mockStatic(LoginUtils.class)) {
                // Set up static method behavior with when/thenReturn
                loginUtilsMockedStatic.when(LoginUtils::getCurrentUserId).thenReturn(USER_ID);
                // Simulate HTTP request using mockMvc.perform
                mockMvc.perform(
                                // Accepts a MockHttpServletRequestBuilder to construct the request
                                // e.g., MockMvcRequestBuilders.post("/bookmark") creates a POST request
                                // MockMvcRequestBuilders.get("/bookmark/get") creates a GET request
                                get("/comment")
                                        .param("id", String.valueOf(ID))
                                        .param("bookmarkId", String.valueOf(BOOKMARK_ID)))
                        // Check response status code using andExpect
                        // isXxx() methods represent expected status codes
                        // e.g., isOk() expects 200, isBadRequest() expects 400
                        .andExpect(status().isOk())
                        // Check specific key-value pairs in JSON response
                        // jsonPath("$.key") specifies the JSON path to check, value(expectedValue) specifies expected value
                        .andExpect(jsonPath("$.code").value(200))
                        .andExpect(jsonPath("$.data.id").value(ID));
            }
        }

        @Test
        @DisplayName("Should return result code of 500")
        void shouldReturnResultCodeOf500() throws Exception {
            String emptyId = "0";
            try (MockedStatic<LoginUtils> loginUtilsMockedStatic = mockStatic(LoginUtils.class)) {
                loginUtilsMockedStatic.when(LoginUtils::getCurrentUserId).thenReturn(USER_ID);
                mockMvc.perform(
                                get("/comment")
                                        .param("id", emptyId)
                                        .param("bookmarkId", String.valueOf(BOOKMARK_ID)))
                        .andExpect(status().isOk())
                        .andExpect(jsonPath("$.code").value(500));
            }
        }
    }

}