package com.github.learndifferent.mtm.manager;

import static com.github.learndifferent.mtm.constant.consist.RedisConstant.MUTE_NOTIFICATIONS;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.redis.core.SetOperations;
import org.springframework.data.redis.core.StringRedisTemplate;

/**
 * Test for NotificationManager using Mockito framework
 * Note: The following comments are generated by Cursor AI and Codeium
 */
@ExtendWith(MockitoExtension.class)
class NotificationManagerTest {

    // Create mock objects
    @Mock
    private StringRedisTemplate redisTemplate;

    @Mock
    private SetOperations<String, String> redisSetOperations;

    // Inject mock objects into the current class instance
    @InjectMocks
    private NotificationManager notificationManager;

    @Test
    @DisplayName("Should return false to indicate that the user has turned on notifications")
    void shouldReturnFalseToIndicateThatTheUserHasTurnedOnNotifications() {
        Long userId = 1L;
        when(redisTemplate.opsForSet()).thenReturn(redisSetOperations);
        when(redisSetOperations.isMember(anyString(), anyString())).thenReturn(false);

        boolean result = notificationManager.checkIfTurnOffNotifications(userId);
        Assertions.assertFalse(result);
    }

    @Test
    @DisplayName("Should turn off notifications")
    void shouldTurnOffNotifications() {
        Long userId = 1L;

        when(redisTemplate.opsForSet()).thenReturn(redisSetOperations);
        when(notificationManager.checkIfTurnOffNotifications(userId)).thenReturn(false);

        notificationManager.turnOnTurnOffNotifications(userId);

        // Use verify() method to check the expected number of method calls
        verify(redisSetOperations, times(0)).remove(MUTE_NOTIFICATIONS, userId);
        verify(redisSetOperations, times(1)).add(MUTE_NOTIFICATIONS, String.valueOf(userId));
    }

}